# -*- coding: utf-8 -*-
"""Telegram Translation Bot - Manually Coded.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUGxWXo_hOx6CBwKc1JAVyi-2ESfWoKW
"""

!pip install telethon httpx pandas
# --- CONFIGURATION ---
API_ID = 123456               # Your API ID (no quotes)
API_HASH = "0e9e4c6API_HASHd27a7b7dca7942"     # Your API Hash (keep quotes)
DEEPSEEK_KEY = "sk-79949bDEEPSEEK_KEYfe23f6f76856"  # Your DeepSeek API Key
CSV_FILE = "user_db.csv"
import pandas as pd
import os, json
import asyncio
import httpx
from telethon import TelegramClient, events
# --- Telegram Bot Logic ---
client = TelegramClient('session_name', API_ID, API_HASH)

# --- Database Setup ---
if not os.path.exists(CSV_FILE):
    df = pd.DataFrame(columns=['user_id', 'base_language'])
    df.to_csv(CSV_FILE, index=False)

def get_user_lang(user_id):
    print("get user lang is called. User ID: ", user_id)
    df = pd.read_csv(CSV_FILE)
    user_row = df[df['user_id'] == user_id]
    return user_row['base_language'].values[0] if not user_row.empty else None

def update_user(user_id, lang):
    df = pd.read_csv(CSV_FILE)
    if str(user_id) in df['user_id'].astype(str).values:
        df.loc[df['user_id'].astype(str) == str(user_id), 'base_language'] = lang
    else:
        new_row = pd.DataFrame({'user_id': [str(user_id)], 'base_language': [lang]})
        df = pd.concat([df, new_row], ignore_index=True)
    df.to_csv(CSV_FILE, index=False)
    print(f"User {user_id} updated.")

#This should not be async.
async def get_deepseek_response(prompt: str, DEEPSEEK_KEY = DEEPSEEK_KEY):
    url = "https://api.deepseek.com/v1/chat/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {DEEPSEEK_KEY}"
    }
    payload = {
        "model": "deepseek-chat",  # You can choose other models like 'deepseek-coder'
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],
        "stream": False
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(url, headers=headers, json=payload, timeout=30.0)
            response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)
            response_data = response.json()
            return response_data['choices'][0]['message']['content']
    except httpx.RequestError as exc:
        print(f"An error occurred while requesting {exc.request.url!r}: {exc}")
        return "Error: Could not connect to DeepSeek API."
    except httpx.HTTPStatusError as exc:
        print(f"Error response {exc.response.status_code} while requesting {exc.request.url!r}: {exc.response.text}")
        return f"Error: DeepSeek API returned status {exc.response.status_code}."
    except KeyError:
        print("Error: Unexpected response format from DeepSeek API.")
        return "Error: Unexpected response from DeepSeek API."
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return "Error: An unexpected error occurred."

def get_incoming_text_metadata_prompt(text):
  prompt = f"""



  Which language is this current text in? Text:
  {text}

  MANDATORY RESPONSE FORMAT:
  {{
      "language": <string | put answer here.>,
      "text": < put original input text>
  }}
  """
  return prompt

def validate_deepseek_response_to_incoming_text_metadata(json_string):
    try:
        data = json.loads(json_string)
        if isinstance(data, dict) and 'language' in data and 'text' in data:
            return data
        else:
            print("Validation failed: 'answer' is JSON but missing 'language' or 'text' fields, or is not a dictionary.")
            return False
    except json.JSONDecodeError:
        print("Validation failed: 'answer' is not a valid JSON string.")
        return False

def get_translation_prompt(text, source_lang, target_lang):
  prompt = f"""
  Translate the following text from {source_lang} to {target_lang}. Only return the translated text.
  Text: {text}
  """
  return prompt

@client.on(events.NewMessage(incoming=True))
async def handler(event):
    if event.is_private:
        my_user_id = 591068843
        target_language = "English"
        user_id = event.sender_id
        text = event.text

        if not text:
          return

        # Get incoming text metadata (language and cleaned text)
        prompt_metadata = get_incoming_text_metadata_prompt(text)
        raw_incText_metadata = await get_deepseek_response(prompt_metadata)
        incText_metadata = validate_deepseek_response_to_incoming_text_metadata(raw_incText_metadata)

        if not incText_metadata: # Handle validation failure
            print("Error: Metadata not found.")
            return

        incText_text = incText_metadata["text"]
        incText_lang = incText_metadata["language"]

        saved_lang = get_user_lang(user_id)

        # If user language not found, save the detected language
        if not saved_lang:
            print(f"User language not found for {user_id}, detecting and saving as {incText_lang}...")
            update_user(user_id, incText_lang)
        else:
            print(f"User {user_id}'s language: {saved_lang}")

        if saved_lang and saved_lang.lower() != incText_lang.lower():
          update_user(user_id, incText_lang)
          print("User updated with latest language s/he/they used.")


        if incText_lang.lower() != target_language.lower():
          #we need translation.
          print("Trying to Translate.")
          prompt_translation = get_translation_prompt(incText_text, incText_lang, target_language)
          translated_text = await get_deepseek_response(prompt_translation)
          translated_text = "🇮🇳 EN: " + translated_text + "\n\n"
          await event.respond(translated_text)

@client.on(events.NewMessage(outgoing=True))
async def outgoing_handler(event):
  if event.is_private:
    recipient_id = event.peer_id.user_id if hasattr(event.peer_id, 'user_id') else event.peer_id
    text_to_send = event.text
    print("outgoing is triggered")

    if not text_to_send:
      return

    target_lang = get_user_lang(recipient_id)

    if not target_lang:
      target_lang = "English"

    # Get incoming text metadata (language and cleaned text)
    prompt_metadata = get_incoming_text_metadata_prompt(text_to_send)
    print("prompt_metadata")
    print(prompt_metadata)
    raw_outText_metadata = await get_deepseek_response(prompt_metadata)
    outText_metadata = validate_deepseek_response_to_incoming_text_metadata(raw_outText_metadata)

    if not outText_metadata: # Handle validation failure
      print("DEEPSEEK output")
      print(raw_outText_metadata)
      print("Error: Metadata not found.")
      return

    outText_text = outText_metadata["text"]
    outText_lang = outText_metadata["language"]

    print("Target Recepient ID:", recipient_id)
    print(target_lang, text_to_send)
    print(outText_lang, outText_text)

    if outText_lang != target_lang:
      print("Trying to Translate.")
      prompt_translation = get_translation_prompt(outText_text, outText_lang, target_lang)
      print(prompt_translation)
      translated_text = await get_deepseek_response(prompt_translation)
      await event.edit(translated_text)





# --- Run the Client ---
print("Bot is starting...")
await client.start()
print("Bot is running. Press Stop in Colab to terminate.")
await client.run_until_disconnected()

